name: Build and Push Docker Image to ACR

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Azure Container Registry using admin credentials
      - name: Log in to ACR
        uses: azure/docker-login@v1
        with:
          login-server: talaacr2024.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: docker build -t talaacr2024.azurecr.io/ipcheck:latest .

      # Push Docker image
      - name: Push Docker image
        run: docker push talaacr2024.azurecr.io/ipcheck:latest
